version: "3.1"

services:
  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:5.5
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=508
      - PGID=508

      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8043

      - ADDOPT_V1_PORT=29812
      - UPGRADE_V1_PORT=29813
      - MANAGER_V1_PORT=29811
      - MANAGER_V2_PORT=29814
      - DISCOVERY_PORT=29810

      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=Etc/UTC
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
      - omada-work:/opt/tplink/EAPController/work
      - omada-properties:/opt/tplink/EAPController/properties

volumes:
  omada-data:
  omada-logs:
  omada-work:
  omada-properties:
